###201 {task}
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "title": "Create a budget plan",
    "description": "Draft a monthly budget plan to track expenses and savings.",
    "completed": "completed",
    "deadline": "2024-10-30",
    "userId":"1"
}